version: '3.7'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file:
      - ./flask/dev.env
    expose:
      - 8080
    links:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
